### PR TITLE
Update set_game.py

### PR DESCRIPTION
**Pull request by lowiq3**
inlined

### CODE REVIEW

**Comment by lowiq3** [comment]
another comment for testing

**Comment by evertqin** [comment]
你可真閒 做個大的project吧

**Comment by lowiq3** [comment]
不闲 我有责任帮你code review 同时也向你学习python 有空的时候 看一下我的comments 恩

On Tuesday, May 17, 2016, Ruogu Qin notifications@github.com wrote:

> 你可真閒 做個大的project吧
> On May 17, 2016 12:11 PM, "lowiq3" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > another comment for testing
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/evertqin/practice/pull/1#issuecomment-219769058
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/evertqin/practice/pull/1#issuecomment-219769891

## 

Jiaming Qiu

**Comment by lowiq3** [comment]
github真是个好东西！

On Tuesday, May 17, 2016, Ruogu Qin notifications@github.com wrote:

> 你可真閒 做個大的project吧
> On May 17, 2016 12:11 PM, "lowiq3" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > another comment for testing
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/evertqin/practice/pull/1#issuecomment-219769058
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/evertqin/practice/pull/1#issuecomment-219769891

## 

Jiaming Qiu

**Comment by evertqin** [comment]
正好熟悉下git flow 这个我特別不熟

**Comment by lowiq3** [comment]
我可以给你讲 git flow

On Tuesday, May 17, 2016, Ruogu Qin notifications@github.com wrote:

> 正好熟悉下git flow 这个我特別不熟
> On May 17, 2016 12:17 PM, "lowiq3" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > github真是个好东西！
> > 
> > On Tuesday, May 17, 2016, Ruogu Qin <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > 你可真閒 做個大的project吧
> > > On May 17, 2016 12:11 PM, "lowiq3" <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>> wrote:
> > > 
> > > > another comment for testing
> > > > 
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/evertqin/practice/pull/1#issuecomment-219769058
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/evertqin/practice/pull/1#issuecomment-219769891
> > 
> > ## 
> > 
> > Jiaming Qiu
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/evertqin/practice/pull/1#issuecomment-219770720
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/evertqin/practice/pull/1#issuecomment-219772369

## 

Jiaming Qiu

**Comment by evertqin** [comment]
Nothing beats practice

**Comment by lowiq3** [comment]
你可真闲

**Comment by lowiq3** [comment]
看我的新头像

**Comment by evertqin** [comment]
whats up with bulldozer

**Comment by lowiq3** [comment]
挖掘机技术哪家强？山东技校找南翔

On Tue, May 17, 2016 at 2:38 PM, Ruogu Qin notifications@github.com wrote:

> whats up with bulldozer
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/evertqin/practice/pull/1#issuecomment-219812857

## 

Jiaming Qiu

**Comment by evertqin** [comment]
翔

**Pull request merged**
